# docker-compose.yml (Final Corrected Version)
# docker-compose.yml (Final Corrected Version)
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      secrets:
        - graph_tenant_id
        - graph_client_id
        - graph_client_secret
        - openai_api_key
    ports:
      - "5000:5000"
    volumes:
       - ./backend:/code/backend
    env_file:
      - ./.env
    command: gunicorn --bind 0.0.0.0:5000 --workers 1 --reload --log-level=debug "app:app"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

networks:
  default:
    name: entra-monitor-dev-network

secrets:
  graph_tenant_id:
    file: ${SECRETS_DIR}\graph_tenant_id.txt
  graph_client_id:
    file: ${SECRETS_DIR}\graph_client_id.txt
  graph_client_secret:
    file: ${SECRETS_DIR}\graph_client_secret.txt
  openai_api_key:
    file: ${SECRETS_DIR}\openai_api_key.txt