# docker-compose.yml
version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app                # hot-reload בפיתוח
    env_file:
      - ./.env                        # משתני סביבה לא-סודיים (למשל CHECK_INTERVAL_MINUTES)
    secrets:                          # ⬅️ mount בזמן הריצה בלבד
      - graph_tenant_id
      - graph_client_id
      - graph_client_secret
      - openai_api_key

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"                     # React dev server → host:3000
    volumes:
      - ./frontend/src:/app/src
    environment:
      - WATCHPACK_POLLING=true        # hot-reload בתוך WSL2 / Docker Desktop
    depends_on:
      - backend

networks:
  default:
    name: entra-monitor-dev-network

secrets:                              # קבצי TXT מחוץ לריפו – ראו הסעיף -3
  graph_tenant_id:
    file: ${SECRETS_DIR}/graph_tenant_id.txt
  graph_client_id:
    file: ${SECRETS_DIR}/graph_client_id.txt
  graph_client_secret:
    file: ${SECRETS_DIR}/graph_client_secret.txt
  openai_api_key:
    file: ${SECRETS_DIR}/openai_api_key.txt
