# ===================================================================
# FILE: docker-compose.yml (FOR DEVELOPMENT)
# PURPOSE: Runs the entire application stack (backend & frontend)
# in a development environment with hot-reloading.
# ===================================================================

services:
  # ====================
  # The Backend Service
  # ====================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ✅ FIX: Ensure PYTHONPATH is correct at runtime!
    command: >
      /bin/sh -c "PYTHONPATH=/app:/app/deps python app.py"
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/deps
    env_file:
      - .env
    secrets:
      - flask_secret_key
      - graph_tenant_id
      - graph_client_id
      - graph_client_secret
      - openai_api_key
      - admin_user
      - admin_pass
    networks:
      - entra-monitor-network
    # Optional: restart policy for dev
    restart: unless-stopped

  # ====================
  # The Frontend Service
  # ====================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=3000
    networks:
      - entra-monitor-network
    depends_on:
      - backend
    restart: unless-stopped

# ====================
# Network definition
# ====================
networks:
  entra-monitor-network:
    name: entra-monitor-dev-network

# ====================
# Secrets definitions
# ====================
secrets:
  flask_secret_key:
    file: ${SECRETS_DIR}/flask_secret_key.txt
  graph_tenant_id:
    file: ${SECRETS_DIR}/graph_tenant_id.txt
  graph_client_id:
    file: ${SECRETS_DIR}/graph_client_id.txt
  graph_client_secret:
    file: ${SECRETS_DIR}/graph_client_secret.txt
  openai_api_key:
    file: ${SECRETS_DIR}/openai_api_key.txt
  admin_user:
    file: ${SECRETS_DIR}/admin_user.txt
  admin_pass:
    file: ${SECRETS_DIR}/admin_pass.txt
