services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # ⭐️ התיקון הקריטי: אנחנו מגדירים את הסודות כאן, בשלב ה-build
      secrets:
        - graph_tenant_id
        - graph_client_id
        - graph_client_secret
        - openai_api_key
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend # שיניתי את הנתיב ל-/app/backend כדי שיתאים ל-Dockerfile החדש
    
    # env_file עדיין נחוץ עבור משתנים לא סודיים
    env_file:
      - ./.env
    
    # ❌ מחקנו את בלוק ה-secrets: שהיה כאן תחת השירות

    command: gunicorn --bind 0.0.0.0:5000 --workers 1 --reload --log-level=debug "backend.app:app"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

networks:
  default:
    name: entra-monitor-dev-network

# בלוק הסודות הראשי נשאר זהה, וממשיך להשתמש במשתנה הסביבה שלך
secrets:
  graph_tenant_id:
    file: ${SECRETS_DIR}/graph_tenant_id.txt
  graph_client_id:
    file: ${SECRETS_DIR}/graph_client_id.txt
  graph_client_secret:
    file: ${SECRETS_DIR}/graph_client_secret.txt
  openai_api_key:
    file: ${SECRETS_DIR}/openai_api_key.txt